# Generated by Django 4.2.7 on 2024-01-21 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='коментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время и дата последней попытки')),
                ('status', models.CharField(choices=[('make', 'Совершена'), ('dont_make', 'Не совершена')], default='Не совершена', max_length=20, verbose_name='Статус')),
                ('response', models.CharField(max_length=100, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Тело письма')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 1, 21, 16, 30, 45, 596270), verbose_name='Время рассылки')),
                ('period', models.CharField(choices=[('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='once_a_day', max_length=20, verbose_name='период')),
                ('status', models.CharField(choices=[('start', 'Запущена'), ('finish', 'Завершена'), ('created', 'Создана')], default='created', max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
