# Generated by Django 4.2.7 on 2024-01-21 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], max_length=20, null=True, verbose_name='период'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 19, 21, 52, 276152), verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='to_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client', to_field='email', verbose_name='кому отправлять'),
        ),
    ]
