# Generated by Django 4.2.7 on 2024-01-21 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_newsletter_options_newsletter_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 20, 14, 41, 507506), verbose_name='Время рассылки'),
        ),
    ]
