# Generated by Django 4.2.7 on 2024-01-23 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_newsletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 23, 20, 32, 7, 382677), verbose_name='Время рассылки'),
        ),
    ]
