# Generated by Django 4.2.7 on 2024-01-24 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_newsletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='period',
            field=models.CharField(choices=[('no', 'Нет'), ('once_a_day', 'Раз в день'), ('once_a_week', 'Раз в неделю'), ('once_a_month', 'Раз в месяц')], default='no', max_length=20, verbose_name='период'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 22, 32, 28, 610297), verbose_name='Время рассылки'),
        ),
    ]
