# Generated by Django 4.2.7 on 2024-01-28 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_newsletter_period_alter_newsletter_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Время рассылки'),
        ),
    ]
